// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEq5maOee8vymZhIdJw4UlByt7yz2PH4Y',
    appId: '1:657931468302:web:abc88a06859307e73ac65f',
    messagingSenderId: '657931468302',
    projectId: 'loopwear-7be61',
    authDomain: 'loopwear-7be61.firebaseapp.com',
    storageBucket: 'loopwear-7be61.firebasestorage.app',
    measurementId: 'G-1RL1RT6P7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwO4dOC4o6wDJPB6JuTaH4QQ5IgcYwWg',
    appId: '1:657931468302:android:1c449a8b3ce107f33ac65f',
    messagingSenderId: '657931468302',
    projectId: 'loopwear-7be61',
    storageBucket: 'loopwear-7be61.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEq5maOee8vymZhIdJw4UlByt7yz2PH4Y',
    appId: '1:657931468302:web:c09ffbb4b4ea282a3ac65f',
    messagingSenderId: '657931468302',
    projectId: 'loopwear-7be61',
    authDomain: 'loopwear-7be61.firebaseapp.com',
    storageBucket: 'loopwear-7be61.firebasestorage.app',
    measurementId: 'G-RF9TSFLW2N',
  );
}
