import 'package:loop_wear/product.dart';

class MyProducts{
  static List<Product> allProducts=[
    ...men,
    ...women,
    ...kids,
    ...summer,
    ...ecoWear,
  ];
  static List<Product> summer = [
    Product(
      id: '1',
      category: "Summer Collection",
      title: "Summer 1",
      description: "Light and breezy summer wear.\nPerfect for hot sunny days.",
      price: "Tk 900",
      image1: "assets/photos/Summer/summer_1_blue_1.jpg",
      image2: "assets/photos/Summer/summer_1_green_1.jpg",
      image3: "assets/photos/Summer/summer_1_pink_1.jpg",
    ),
    Product(
      id: '2',
      category: "Summer Collection",
      title: "Summer 2",
      description: "Cool and comfortable outfit.\nVibrant colors ideal for summer.",
      price: "Tk 920",
      image1: "assets/photos/Summer/summer_2_pink_1.jpg",
      image2: "assets/photos/Summer/summer_2_white_1.jpg",
      image3: "assets/photos/Summer/summer_2_yellow_1.jpg",
    ),
    Product(
      id: '3',
      category: "Summer Collection",
      title: "Summer 3",
      description: "Soft and airy fabric.\nGreat for casual summer outings.",
      price: "Tk 910",
      image1: "assets/photos/Summer/summer_3_beige_1.jpg",
      image2: "assets/photos/Summer/summer_3_blue_1.jpg",
      image3: "assets/photos/Summer/summer_3_green_1.jpg",
    ),
    Product(
      id: '4',
      category: "Summer Collection",
      title: "Summer 4",
      description: "Comfortable summer top and bottom set.\nBreathable and lightweight.",
      price: "Tk 940",
      image1: "assets/photos/Summer/summer_4_beige_1.jpg",
      image2: "assets/photos/Summer/summer_4_brown_1.jpg",
      image3: "assets/photos/Summer/summer_4_green_1.jpg",
    ),
    Product(
      id: '5',
      category: "Summer Collection",
      title: "Summer 5",
      description: "Bright and stylish summer outfit.\nSoft material perfect for kids and adults.",
      price: "Tk 950",
      image1: "assets/photos/Summer/summer_5_green_1.jpg",
      image2: "assets/photos/Summer/summer_5_pink_1.jpg",
      image3: "assets/photos/Summer/summer_5_white_1.jpg",
    ),
    Product(
      id: '6',
      category: "Summer Collection",
      title: "Summer 6",
      description: "Vibrant colors for sunny days.\nLightweight and comfortable fabric.",
      price: "Tk 960",
      image1: "assets/photos/Summer/summer_6_green_1.jpg",
      image2: "assets/photos/Summer/summer_6_purple_1.jpg",
      image3: "assets/photos/Summer/summer_6_white_1.jpg",
    ),
    Product(
      id: '7',
      category: "Summer Collection",
      title: "Summer 7",
      description: "Airy summer clothing.\nSoft and perfect for outdoor activities.",
      price: "Tk 940",
      image1: "assets/photos/Summer/summer_7_beige_1.jpg",
      image2: "assets/photos/Summer/summer_7_blue_1.jpg",
      image3: "assets/photos/Summer/summer_7_green_1.jpg",
    ),
    Product(
      id: '8',
      category: "Summer Collection",
      title: "Summer 8",
      description: "Casual summer outfit.\nLight fabric and bright colors.",
      price: "Tk 950",
      image1: "assets/photos/Summer/summer_8_green_1.jpg",
      image2: "assets/photos/Summer/summer_8_red_1.jpg",
      image3: "assets/photos/Summer/summer_8_yellow_1.jpg",
    ),
    Product(
      id: '9',
      category: "Summer Collection",
      title: "Summer 9",
      description: "Comfortable summer wear.\nStylish and vibrant colors.",
      price: "Tk 970",
      image1: "assets/photos/Summer/summer_9_red_1.jpg",
      image2: "assets/photos/Summer/summer_9_blue_1.jpg",
      image3: "assets/photos/Summer/summer_9_navy_1.jpg",
    ),
  ];

  static List<Product> winter=[
    ...kidsJackets,
    ...sweatersM,
    ...sweatersW,
  ];

  static List<Product> shirts = [
    Product(
      id: '10',
      title: "Men's Classic Shirt 1",
      category: "Men",
      image1: "assets/photos/Men/shirt_1_black.jpg",
      image2: "assets/photos/Men/shirt_1_blue.jpg",
      image3: "assets/photos/Men/shirt_1_maroon.jpg",
      description: "A comfortable, stylish shirt for daily wear.\nPerfect for casual and semi-formal occasions.",
      price: "Tk 1250",
    ),
    Product(
      id: '11',
      title: "Men's Classic Shirt 2",
      category: "Men",
      image1: "assets/photos/Men/shirt_2_black.jpg",
      image2: "assets/photos/Men/shirt_2_blue.jpg",
      image3: "assets/photos/Men/shirt_2_green.jpg",
      description: "Premium cotton shirt for all-day comfort.\nMatches well with jeans or formal trousers.",
      price: "Tk 1300",
    ),
    Product(
      id: '12',
      title: "Men's Classic Shirt 3",
      category: "Men",
      image1: "assets/photos/Men/shirt_3_beige.jpg",
      image2: "assets/photos/Men/shirt_3_blue.jpg",
      image3: "assets/photos/Men/shirt_3_green.jpg",
      description: "Elegant shirt with a perfect fit.\nIdeal for work or casual outings.",
      price: "Tk 1280",
    ),
    Product(
      id: '13',
      title: "Men's Classic Shirt 4",
      category: "Men",
      image1: "assets/photos/Men/shirt_4_beige.jpg",
      image2: "assets/photos/Men/shirt_4_black.jpg",
      image3: "assets/photos/Men/shirt_4_blue.jpg",
      description: "Modern style shirt for versatile use.\nSoft fabric ensures comfort all day.",
      price: "Tk 1350",
    ),
    Product(
      id: '14',
      title: "Men's Classic Shirt 5",
      category: "Men",
      image1: "assets/photos/Men/shirt_5_green.jpg",
      image2: "assets/photos/Men/shirt_5_maroon.jpg",
      image3: "assets/photos/Men/shirt_5_white.jpg",
      description: "Trendy and elegant shirt for any occasion.\nPairs perfectly with casual or formal wear.",
      price: "Tk 1400",
    ),
  ];
  static List<Product> tShirts = [
    Product(
      id: '15',
      title: "Men's Casual T-Shirt 1",
      category: "Men",
      image1: "assets/photos/Men/tshirt_1_beige.jpg",
      image2: "assets/photos/Men/tshirt_1_blue.jpg",
      image3: "assets/photos/Men/tshirt_1_pink.jpg",
      description: "Soft and breathable cotton t-shirt.\nIdeal for summer and casual outings.",
      price: "Tk 900",
    ),
    Product(
      id: '16',
      title: "Men's Casual T-Shirt 2",
      category: "Men",
      image1: "assets/photos/Men/tshirt_2_black.jpg",
      image2: "assets/photos/Men/tshirt_2_blue.jpg",
      image3: "assets/photos/Men/tshirt_2_red.jpg",
      description: "Stylish t-shirt for everyday wear.\nPairs easily with jeans or shorts.",
      price: "Tk 950",
    ),
    Product(
      id: '17',
      title: "Men's Casual T-Shirt 3",
      category: "Men",
      image1: "assets/photos/Men/tshirt_3_beige.jpg",
      image2: "assets/photos/Men/tshirt_3_blue.jpg",
      image3: "assets/photos/Men/tshirt_3_green.jpg",
      description: "Comfortable fit with vibrant colors.\nPerfect for casual and active use.",
      price: "Tk 920",
    ),
    Product(
      id: '18',
      title: "Men's Casual T-Shirt 4",
      category: "Men",
      image1: "assets/photos/Men/tshirt_4_blue.jpg",
      image2: "assets/photos/Men/tshirt_4_green.jpg",
      image3: "assets/photos/Men/tshirt_4_purple.jpg",
      description: "Lightweight t-shirt for daily wear.\nKeeps you comfortable in all conditions.",
      price: "Tk 940",
    ),
    Product(
      id: '19',
      title: "Men's Casual T-Shirt 5",
      category: "Men",
      image1: "assets/photos/Men/tshirt_5_brown.jpg",
      image2: "assets/photos/Men/tshirt_5_green.jpg",
      image3: "assets/photos/Men/tshirt_5_red.jpg",
      description: "Durable cotton t-shirt with vibrant colors.\nPerfect for casual outings or sports.",
      price: "Tk 970",
    ),
    Product(
      id: '20',
      title: "Men's Casual T-Shirt 6",
      category: "Men",
      image1: "assets/photos/Men/tshirt_6_yellow.jpg",
      image2: "assets/photos/Men/tshirt_6_green.jpg",
      image3: "assets/photos/Men/tshirt_6_white.jpg",
      description: "Trendy and bright t-shirt for daily use.\nPairs well with jeans or shorts.",
      price: "Tk 990",
    ),
  ];
  static List<Product> blazers = [
    Product(
      id: '21',
      title: "Men's Blazer 1",
      category: "Men",
      image1: "assets/photos/Men/blazar_1_blue.jpg",
      image2: "assets/photos/Men/blazar_1_brown.jpg",
      image3: "assets/photos/Men/blazar_1_green.jpg",
      description: "Smart blazer for formal occasions.\nPerfect for office or evening events.",
      price: "Tk 3200",
    ),
    Product(
      id: '22',
      title: "Men's Blazer 2",
      category: "Men",
      image1: "assets/photos/Men/blazar_2_beige.jpg",
      image2: "assets/photos/Men/blazar_2_green.jpg",
      image3: "assets/photos/Men/blazar_2_grey.jpg",
      description: "Classic blazer with elegant cut.\nIdeal for business or formal gatherings.",
      price: "Tk 3300",
    ),
    Product(
      id: '23',
      title: "Men's Blazer 3",
      category: "Men",
      image1: "assets/photos/Men/blazar_3_beige.jpg",
      image2: "assets/photos/Men/blazar_3_black.jpg",
      image3: "assets/photos/Men/blazar_3_blue.jpg",
      description: "Premium fabric blazer with perfect fit.\nGreat for meetings or formal events.",
      price: "Tk 3400",
    ),
    Product(
      id: '24',
      title: "Men's Blazer 4",
      category: "Men",
      image1: "assets/photos/Men/blazar_4_beige.jpg",
      image2: "assets/photos/Men/blazar_4_green.jpg",
      image3: "assets/photos/Men/blazar_4_grey.jpg",
      description: "Elegant and versatile blazer.\nSuitable for office, dinners, or formal occasions.",
      price: "Tk 3500",
    ),
    Product(
      id: '25',
      title: "Men's Blazer 5",
      category: "Men",
      image1: "assets/photos/Men/blazar_5_brown.jpg",
      image2: "assets/photos/Men/blazar_5_grey.jpg",
      image3: "assets/photos/Men/blazar_5_white.jpg",
      description: "Stylish blazer with modern design.\nPerfect for smart casual and formal wear.",
      price: "Tk 3600",
    ),
    Product(
      id: '26',
      title: "Men's Blazer 6",
      category: "Men",
      image1: "assets/photos/Men/blazar_6_blue.jpg",
      image2: "assets/photos/Men/blazar_6_green.jpg",
      image3: "assets/photos/Men/blazar_6_red.jpg",
      description: "Premium blazer with vibrant color options.\nFits perfectly for formal occasions.",
      price: "Tk 3700",
    ),
  ];
  static List<Product> pants = [
    Product(
      id: '27',
      title: "Men's Pant 1",
      category: "Men",
      image1: "assets/photos/Men/pant_1_black.jpg",
      image2: "assets/photos/Men/pant_1_blue.jpg",
      image3: "assets/photos/Men/pant_1_grey.jpg",
      description: "Comfortable and stylish pants.\nPerfect for casual or office wear.",
      price: "Tk 1500",
    ),
    Product(
      id: '28',
      title: "Men's Pant 2",
      category: "Men",
      image1: "assets/photos/Men/pant_2_beige.jpg",
      image2: "assets/photos/Men/pant_2_black.jpg",
      image3: "assets/photos/Men/pant_2_red.jpg",
      description: "Durable pants with modern fit.\nIdeal for work or casual outings.",
      price: "Tk 1550",
    ),
    Product(
      id: '29',
      title: "Men's Pant 3",
      category: "Men",
      image1: "assets/photos/Men/pant_3_blue.jpg",
      image2: "assets/photos/Men/pant_3_green.jpg",
      image3: "assets/photos/Men/pant_3_grey.jpg",
      description: "Classic pants with comfortable fabric.\nPerfect for daily or office wear.",
      price: "Tk 1600",
    ),
    Product(
      id: '30',
      title: "Men's Pant 4",
      category: "Men",
      image1: "assets/photos/Men/pant_4_black.jpg",
      image2: "assets/photos/Men/pant_4_blue.jpg",
      image3: "assets/photos/Men/pant_4_grey.jpg",
      description: "Modern pants with perfect fit.\nIdeal for casual or formal occasions.",
      price: "Tk 1620",
    ),
    Product(
      id: '31',
      title: "Men's Pant 5",
      category: "Men",
      image1: "assets/photos/Men/pant_5_black.jpg",
      image2: "assets/photos/Men/pant_5_blue.jpg",
      image3: "assets/photos/Men/pant_5_grey.jpg",
      description: "Stylish pants with versatile colors.\nPerfect for work or casual use.",
      price: "Tk 1650",
    ),
    Product(
      id: '32',
      title: "Men's Pant 6",
      category: "Men",
      image1: "assets/photos/Men/pant_6_beige.jpg",
      image2: "assets/photos/Men/pant_6_green.jpg",
      image3: "assets/photos/Men/pant_6_white.jpg",
      description: "Comfortable pants with modern style.\nGreat for daily or formal wear.",
      price: "Tk 1680",
    ),
    Product(
      id: '33',
      title: "Men's Pant 7",
      category: "Men",
      image1: "assets/photos/Men/pant_7_blue.jpg",
      image2: "assets/photos/Men/pant_7_green.jpg",
      image3: "assets/photos/Men/pant_7_white.jpg",
      description: "Versatile pants with premium fabric.\nIdeal for casual and formal occasions.",
      price: "Tk 1700",
    ),
  ];
  static List<Product> sweatersM = [
    Product(
      id: '34',
      title: "Men's Sweater 1",
      category: "Men",
      image1: "assets/photos/Men/sweater_1_black.jpg",
      image2: "assets/photos/Men/sweater_1_brown.jpg",
      image3: "assets/photos/Men/sweater_1_green.jpg",
      description: "Warm and comfortable sweater.\nPerfect for chilly days and casual outings.",
      price: "Tk 2000",
    ),
    Product(
      id: '35',
      title: "Men's Sweater 2",
      category: "Men",
      image1: "assets/photos/Men/sweater_2_blue.jpg",
      image2: "assets/photos/Men/sweater_2_green.jpg",
      image3: "assets/photos/Men/sweater_2_red.jpg",
      description: "Cozy sweater with vibrant colors.\nIdeal for winter or casual wear.",
      price: "Tk 2050",
    ),
    Product(
      id: '36',
      title: "Men's Sweater 3",
      category: "Men",
      image1: "assets/photos/Men/sweater_3_brown.jpg",
      image2: "assets/photos/Men/sweater_3_green.jpg",
      image3: "assets/photos/Men/sweater_3_pink.jpg",
      description: "Elegant sweater with comfortable fabric.\nGreat for daily or office use.",
      price: "Tk 2100",
    ),
    Product(
      id: '37',
      title: "Men's Sweater 4",
      category: "Men",
      image1: "assets/photos/Men/sweater_4_brown.jpg",
      image2: "assets/photos/Men/sweater_4_grey.jpg",
      image3: "assets/photos/Men/sweater_4_red.jpg",
      description: "Stylish sweater with perfect fit.\nSuitable for casual and semi-formal occasions.",
      price: "Tk 2150",
    ),
    Product(
      id: '38',
      title: "Men's Sweater 5",
      category: "Men",
      image1: "assets/photos/Men/sweater_5_blue.jpg",
      image2: "assets/photos/Men/sweater_5_brown.jpg",
      image3: "assets/photos/Men/sweater_5_grey.jpg",
      description: "Comfortable sweater with trendy colors.\nPerfect for office or casual outings.",
      price: "Tk 2200",
    ),
    Product(
      id: '39',
      title: "Men's Sweater 6",
      category: "Men",
      image1: "assets/photos/Men/sweater_6_beige.jpg",
      image2: "assets/photos/Men/sweater_6_brown.jpg",
      image3: "assets/photos/Men/sweater_6_grey.jpg",
      description: "Premium sweater with soft fabric.\nIdeal for winter and casual wear.",
      price: "Tk 2250",
    ),
  ];
  static List<Product> men = [
    ...shirts,
    ...tShirts,
    ...blazers,
    ...pants,
    ...sweatersM,
  ];

  static List<Product> bottoms = [

    Product(
      id: '40',
      title: "Classic Straight Pants",
      category: "Women",
      image1: "assets/photos/Women/bottom_1_brown.jpg",
      image2: "assets/photos/Women/bottom_1_pink.jpg",
      image3: "assets/photos/Women/bottom_1_white.jpg",
      description: "Elegant straight-fit pants for everyday comfort.\nSoft fabric with a flattering silhouette.",
      price: "Tk 1890",
    ),

    Product(
      id: '41',
      title: "Modern Casual Trousers",
      category: "Women",
      image1: "assets/photos/Women/bottom_2_beige.jpg",
      image2: "assets/photos/Women/bottom_2_black.jpg",
      image3: "assets/photos/Women/bottom_2_white.jpg",
      description: "Stylish trousers perfect for casual or office wear.\nComfortable stretch fabric with modern cut.",
      price: "Tk 1950",
    ),

    Product(
      id: '42',
      title: "Slim Fit Tailored Pants",
      category: "Women",
      image1: "assets/photos/Women/bottom_3_beige.jpg",
      image2: "assets/photos/Women/bottom_3_maroon.jpg",
      image3: "assets/photos/Women/bottom_3_white.jpg",
      description: "Smart slim-fit pants with a tailored look.\nGreat for professional or smart casual outfits.",
      price: "Tk 1990",
    ),

    Product(
      id: '43',
      title: "Relaxed Fit Wide Pants",
      category: "Women",
      image1: "assets/photos/Women/bottom_4_beige.jpg",
      image2: "assets/photos/Women/bottom_4_grey.jpg",
      image3: "assets/photos/Women/bottom_4_white.jpg",
      description: "Comfortable wide-leg pants for relaxed style.\nBreathable material perfect for all day wear.",
      price: "Tk 2050",
    ),

    Product(
      id: '44',
      title: "Minimal Chic Trousers",
      category: "Women",
      image1: "assets/photos/Women/bottom_5_black.jpg",
      image2: "assets/photos/Women/bottom_5_white.jpg",
      image3: "assets/photos/Women/bottom_5_yellow.jpg",
      description: "Clean and minimal design for modern fashion.\nPairs perfectly with shirts and tops.",
      price: "Tk 2100",
    ),

    Product(
      id: '45',
      title: "Soft Casual Bottoms",
      category: "Women",
      image1: "assets/photos/Women/bottom_6_brown.jpg",
      image2: "assets/photos/Women/bottom_6_pink.jpg",
      image3: "assets/photos/Women/bottom_6_white.jpg",
      description: "Lightweight bottoms designed for comfort.\nStylish enough for daily wear.",
      price: "Tk 1890",
    ),

    Product(
      id: '46',
      title: "Elegant Slim Pants",
      category: "Women",
      image1: "assets/photos/Women/bottom_7_black.jpg",
      image2: "assets/photos/Women/bottom_7_blue.jpg",
      image3: "assets/photos/Women/bottom_7_maroon.jpg",
      description: "Sophisticated slim pants with clean lines.\nPerfect for office or formal outfits.",
      price: "Tk 2150",
    ),

  ];
  static List<Product> coords = [

    Product(
      id: '47',
      title:"Chic Co-Ord Set",
      category:"Women",
      image1:"assets/photos/Women/coord_1_brown.jpg",
      image2:"assets/photos/Women/coord_1_multi.jpg",
      image3:"assets/photos/Women/coord_1_purple.jpg",
      description:"Trendy matching co-ord set for modern fashion.\nComfortable fabric with stylish look.",
      price:"Tk 2950",
    ),

    Product(
      id: '48',
      title:"Denim Style Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_2_brown.jpg",
      image2:"assets/photos/Women/coord_2_denim.jpg",
      image3:"assets/photos/Women/coord_2_multi.jpg",
      description:"Casual denim inspired two piece outfit.\nStylish and comfortable for daily wear.",
      price:"Tk 3100",
    ),

    Product(
      id: '49',
      title:"Elegant Two Piece Set",
      category:"Women",
      image1:"assets/photos/Women/coord_3_blue.jpg",
      image2:"assets/photos/Women/coord_3_brown.jpg",
      image3:"assets/photos/Women/coord_3_maroon.jpg",
      description:"Beautiful coordinated set for a polished style.\nPerfect for outings and casual events.",
      price:"Tk 3050",
    ),

    Product(
      id: '50',
      title:"Soft Neutral Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_4_beige.jpg",
      image2:"assets/photos/Women/coord_4_blue.jpg",
      image3:"assets/photos/Women/coord_4_white.jpg",
      description:"Minimal co-ord outfit with elegant neutral tones.\nComfortable fabric with relaxed fit.",
      price:"Tk 2990",
    ),

    Product(
      id: '51',
      title:"Evening Co-Ord Outfit",
      category:"Women",
      image1:"assets/photos/Women/coord_5_black.jpg",
      image2:"assets/photos/Women/coord_5_maroon.jpg",
      image3:"assets/photos/Women/coord_5_white.jpg",
      description:"Sophisticated co-ord set designed for elegance.\nModern silhouette with premium material.",
      price:"Tk 3200",
    ),

    Product(
      id: '52',
      title:"Urban Casual Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_6_black.jpg",
      image2:"assets/photos/Women/coord_6_green.jpg",
      image3:"assets/photos/Women/coord_6_white.jpg",
      description:"Urban style coordinated outfit for trendy looks.\nPerfect for modern street fashion.",
      price:"Tk 3150",
    ),

    Product(
      id: '53',
      title:"Fresh Summer Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_7_green.jpg",
      image2:"assets/photos/Women/coord_7_multi.jpg",
      image3:"assets/photos/Women/coord_7_white.jpg",
      description:"Light and colorful co-ord set for summer.\nComfortable breathable material.",
      price:"Tk 3000",
    ),

    Product(
      id: '54',
      title:"Modern Fashion Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_8_black.jpg",
      image2:"assets/photos/Women/coord_8_brown.jpg",
      image3:"assets/photos/Women/coord_8_green.jpg",
      description:"Stylish coordinated outfit with modern design.\nPerfect for casual fashion lovers.",
      price:"Tk 3250",
    ),

  ];
  static List<Product> dresses = [

    Product(
      id: '55',
      title:"Elegant Evening Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_1_blue.jpg",
      image2:"assets/photos/Women/dress_1_purple.jpg",
      image3:"assets/photos/Women/dress_1_red.jpg",
      description:"Beautiful dress perfect for evening events.\nSoft flowing fabric with elegant style.",
      price:"Tk 2750",
    ),

    Product(
      id: '56',
      title:"Party Style Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_2_blue.jpg",
      image2:"assets/photos/Women/dress_2_maroon.jpg",
      image3:"assets/photos/Women/dress_2_violet.jpg",
      description:"Stylish party dress with modern silhouette.\nPerfect for celebrations and occasions.",
      price:"Tk 2890",
    ),

    Product(
      id: '57',
      title:"Casual Midi Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_3_black.jpg",
      image2:"assets/photos/Women/dress_3_blue.jpg",
      image3:"assets/photos/Women/dress_3_brown.jpg",
      description:"Comfortable midi dress for everyday fashion.\nSoft fabric with relaxed fit.",
      price:"Tk 2450",
    ),

    Product(
      id: '58',
      title:"Summer Floral Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_4_black.jpg",
      image2:"assets/photos/Women/dress_4_pink.jpg",
      image3:"assets/photos/Women/dress_4_yellow.jpg",
      description:"Light summer dress with vibrant colors.\nPerfect for warm weather styling.",
      price:"Tk 2390",
    ),

    Product(
      id: '59',
      title:"Minimal Elegant Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_5_black.jpg",
      image2:"assets/photos/Women/dress_5_blue.jpg",
      image3:"assets/photos/Women/dress_5_white.jpg",
      description:"Simple elegant dress with modern design.\nComfortable and stylish for any occasion.",
      price:"Tk 2550",
    ),

    Product(
      id: '60',
      title:"Soft Casual Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_6_green.jpg",
      image2:"assets/photos/Women/dress_6_white.jpg",
      image3:"assets/photos/Women/dress_6_yellow.jpg",
      description:"Lightweight casual dress for daily comfort.\nRelaxed silhouette with soft material.",
      price:"Tk 2290",
    ),

  ];
  static List<Product> sweatersW = [

    Product(
      id: '61',
      title:"Classic Knit Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_1_blue.jpg",
      image2:"assets/photos/Women/sweater_1_brown.jpg",
      image3:"assets/photos/Women/sweater_1_maroon.jpg",
      description:"Warm knit sweater designed for comfort.\nPerfect winter essential for daily wear.",
      price:"Tk 2190",
    ),

    Product(
      id: '62',
      title:"Soft Winter Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_2_beige.jpg",
      image2:"assets/photos/Women/sweater_2_black.jpg",
      image3:"assets/photos/Women/sweater_2_blue.jpg",
      description:"Stylish winter sweater with cozy fabric.\nKeeps you warm while looking elegant.",
      price:"Tk 2250",
    ),

    Product(
      id: '63',
      title:"Modern Knit Pullover",
      category:"Women",
      image1:"assets/photos/Women/sweater_3_blue.jpg",
      image2:"assets/photos/Women/sweater_3_green.jpg",
      image3:"assets/photos/Women/sweater_3_white.jpg",
      description:"Contemporary pullover sweater for winter fashion.\nComfortable knit with relaxed fit.",
      price:"Tk 2290",
    ),

    Product(
      id: '64',
      title:"Soft Pastel Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_4_beige.jpg",
      image2:"assets/photos/Women/sweater_4_pink.jpg",
      image3:"assets/photos/Women/sweater_4_white.jpg",
      description:"Beautiful pastel sweater with soft texture.\nPerfect for cozy winter outfits.",
      price:"Tk 2190",
    ),

    Product(
      id: '65',
      title:"Minimal Knit Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_5_beige.jpg",
      image2:"assets/photos/Women/sweater_5_black.jpg",
      image3:"assets/photos/Women/sweater_5_green.jpg",
      description:"Clean minimalist sweater for modern style.\nWarm and comfortable winter clothing.",
      price:"Tk 2300",
    ),

    Product(
      id: '66',
      title:"Warm Casual Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_6_beige.jpg",
      image2:"assets/photos/Women/sweater_6_brown.jpg",
      image3:"assets/photos/Women/sweater_6_maroon.jpg",
      description:"Classic sweater with relaxed winter design.\nSoft knit fabric for everyday warmth.",
      price:"Tk 2350",
    ),

    Product(
      id: '67',
      title:"Elegant Winter Pullover",
      category:"Women",
      image1:"assets/photos/Women/sweater_7_beige.jpg",
      image2:"assets/photos/Women/sweater_7_blue.jpg",
      image3:"assets/photos/Women/sweater_7_pink.jpg",
      description:"Elegant pullover sweater for winter outfits.\nStylish look with cozy warmth.",
      price:"Tk 2390",
    ),

  ];
  static List<Product> tops = [

    Product(
      id: '68',
      title:"Casual Cotton Top",
      category:"Women",
      image1:"assets/photos/Women/tops_1_blue.jpg",
      image2:"assets/photos/Women/tops_1_pink.jpg",
      image3:"assets/photos/Women/tops_1_yellow.jpg",
      description:"Soft cotton top perfect for daily outfits.\nComfortable fit with modern design.",
      price:"Tk 1290",
    ),

    Product(
      id: '69',
      title:"Minimal Everyday Top",
      category:"Women",
      image1:"assets/photos/Women/tops_2_beige.jpg",
      image2:"assets/photos/Women/tops_2_black.jpg",
      image3:"assets/photos/Women/tops_2_blue.jpg",
      description:"Simple stylish top for everyday fashion.\nLight fabric with relaxed comfort.",
      price:"Tk 1350",
    ),

    Product(
      id: '70',
      title:"Modern Casual Top",
      category:"Women",
      image1:"assets/photos/Women/tops_3_blue.jpg",
      image2:"assets/photos/Women/tops_3_pink.jpg",
      image3:"assets/photos/Women/tops_3_white.jpg",
      description:"Trendy top with modern minimal style.\nComfortable fabric perfect for casual wear.",
      price:"Tk 1390",
    ),

    Product(
      id: '71',
      title:"Elegant Daily Top",
      category:"Women",
      image1:"assets/photos/Women/tops_4_beige.jpg",
      image2:"assets/photos/Women/tops_4_pink.jpg",
      image3:"assets/photos/Women/tops_4_white.jpg",
      description:"Elegant simple top suitable for any outfit.\nSoft material with stylish look.",
      price:"Tk 1450",
    ),

    Product(
      id: '72',
      title:"Light Summer Top",
      category:"Women",
      image1:"assets/photos/Women/tops_5_white_b.jpg",
      image2:"assets/photos/Women/tops_5_white_p.jpg",
      image3:"assets/photos/Women/tops_5_yellow.jpg",
      description:"Light breathable summer top for comfort.\nPerfect for warm weather fashion.",
      price:"Tk 1320",
    ),

    Product(
      id: '73',
      title:"Soft Casual Blouse",
      category:"Women",
      image1:"assets/photos/Women/tops_6_pink.jpg",
      image2:"assets/photos/Women/tops_6_white.jpg",
      image3:"assets/photos/Women/tops_6_yellow.jpg",
      description:"Comfortable blouse with elegant design.\nPerfect for casual daily wear.",
      price:"Tk 1400",
    ),

    Product(
      id: '74',
      title:"Bright Fashion Top",
      category:"Women",
      image1:"assets/photos/Women/tops_7_pink.jpg",
      image2:"assets/photos/Women/tops_7_red.jpg",
      image3:"assets/photos/Women/tops_7_yellow.jpg",
      description:"Bright colorful top for trendy style.\nPerfect for casual modern outfits.",
      price:"Tk 1380",
    ),

  ];
  static List<Product> women = [
    ...bottoms,
    ...coords,
    ...dresses,
    ...sweatersW,
    ...tops,
  ];

  static List<Product> kidsRegular = [
    Product(
      id: '75',
      category: "Kids",
      title: "Kids Regular 1",
      description: "Comfortable cotton t-shirt suitable for daily wear.\nEasy to wash and soft on skin.",
      price: "Tk 600",
      image1: "assets/photos/Kids/regular_1_beige.jpg",
      image2: "assets/photos/Kids/regular_1_blue.jpg",
      image3: "assets/photos/Kids/regular_1_green.jpg",
    ),
    Product(
      id: '76',
      category: "Kids",
      title: "Kids Regular 2",
      description: "Soft and breathable fabric for active kids.\nPerfect for school and playtime.",
      price: "Tk 650",
      image1: "assets/photos/Kids/regular_2_beige.jpg",
      image2: "assets/photos/Kids/regular_2_blue.jpg",
      image3: "assets/photos/Kids/regular_2_brown.jpg",
    ),
    Product(
      id: '77',
      category: "Kids",
      title: "Kids Regular 3",
      description: "Durable t-shirt with vibrant colors.\nComfortable and easy to maintain.",
      price: "Tk 620",
      image1: "assets/photos/Kids/regular_3_beige.jpg",
      image2: "assets/photos/Kids/regular_3_multi.jpg",
      image3: "assets/photos/Kids/regular_3_yellow.jpg",
    ),
    Product(
      id: '78',
      category: "Kids",
      title: "Kids Regular 4",
      description: "Lightweight cotton top for everyday comfort.\nIdeal for indoor and outdoor activities.",
      price: "Tk 610",
      image1: "assets/photos/Kids/regular_4_blue.jpg",
      image2: "assets/photos/Kids/regular_4_green.jpg",
      image3: "assets/photos/Kids/regular_4_pink.jpg",
    ),
    Product(
      id: '79',
      category: "Kids",
      title: "Kids Regular 5",
      description: "Soft, stretchable t-shirt with fun design.\nGreat for casual outings and playtime.",
      price: "Tk 630",
      image1: "assets/photos/Kids/regular_5_black.jpg",
      image2: "assets/photos/Kids/regular_5_blue.jpg",
      image3: "assets/photos/Kids/regular_5_white.jpg",
    ),
    Product(
      id: '80',
      category: "Kids",
      title: "Kids Regular 6",
      description: "Cozy cotton t-shirt with vibrant color.\nEasy to wash and maintain for kids.",
      price: "Tk 600",
      image1: "assets/photos/Kids/regular_6_white.jpg",
      image2: "assets/photos/Kids/regular_6_blue.jpg",
      image3: "assets/photos/Kids/regular_6_maroon.jpg",
    ),
  ];
  static List<Product> kidsNight = [
    Product(
      id: '81',
      category: "Kids",
      title: "Kids Pajama 1",
      description: "Soft pajama set for night comfort.\nBreathable fabric for peaceful sleep.",
      price: "Tk 700",
      image1: "assets/photos/Kids/pajama_1_1.jpg",
      image2: "assets/photos/Kids/pajama_1_2.jpg",
      image3: "assets/photos/Kids/pajama_1_3.jpg",
    ),
    Product(
      id: '82',
      category: "Kids",
      title: "Kids Pajama 2",
      description: "Comfortable nightwear set for kids.\nSoft fabric for a restful sleep.",
      price: "Tk 720",
      image1: "assets/photos/Kids/pajama_2_1.jpg",
      image2: "assets/photos/Kids/pajama_2_2.jpg",
      image3: "assets/photos/Kids/pajama_2_3.jpg",
    ),
    Product(
      id: '83',
      category: "Kids",
      title: "Kids Pajama 3",
      description: "Lightweight cotton pajamas for nightwear.\nSafe and soft for kids’ skin.",
      price: "Tk 710",
      image1: "assets/photos/Kids/pajama_3_1.jpg",
      image2: "assets/photos/Kids/pajama_3_2.jpg",
      image3: "assets/photos/Kids/pajama_3_3.jpg",
    ),
    Product(
      id: '84',
      category: "Kids",
      title: "Kids Pajama 4",
      description: "Warm pajama set suitable for cooler nights.\nSoft and durable material.",
      price: "Tk 730",
      image1: "assets/photos/Kids/pajama_4_1.jpg",
      image2: "assets/photos/Kids/pajama_4_2.jpg",
      image3: "assets/photos/Kids/pajama_4_3.jpg",
    ),
    Product(
      id: '85',
      category: "Kids",
      title: "Kids Pajama 5",
      description: "Cozy nightwear set with fun patterns.\nIdeal for a comfortable sleep.",
      price: "Tk 740",
      image1: "assets/photos/Kids/pajama_5_1.jpg",
      image2: "assets/photos/Kids/pajama_5_2.jpg",
      image3: "assets/photos/Kids/pajama_5_3.jpg",
    ),
  ];
  static List<Product> kidsDenims = [
    Product(
      id: '86',
      category: "Kids",
      title: "Kids Denim 1",
      description: "Durable denim pants for active kids.\nComfortable for daily wear.",
      price: "Tk 800",
      image1: "assets/photos/Kids/denim_1_beige.jpg",
      image2: "assets/photos/Kids/denim_1_black.jpg",
      image3: "assets/photos/Kids/denim_1_brown.jpg",
    ),
    Product(
      id: '87',
      category: "Kids",
      title: "Kids Denim 2",
      description: "Soft denim pants with stylish design.\nPerfect for school or outings.",
      price: "Tk 820",
      image1: "assets/photos/Kids/denim_2_blue.jpg",
      image2: "assets/photos/Kids/denim_2_pink.jpg",
      image3: "assets/photos/Kids/denim_2_white.jpg",
    ),
    Product(
      id: '88',
      category: "Kids",
      title: "Kids Denim 3",
      description: "Comfortable and durable denim pants.\nEasy to pair with any top.",
      price: "Tk 810",
      image1: "assets/photos/Kids/denim_3_black.jpg",
      image2: "assets/photos/Kids/denim_3_blue.jpg",
      image3: "assets/photos/Kids/denim_3_red.jpg",
    ),
    Product(
      id: '89',
      category: "Kids",
      title: "Kids Denim 4",
      description: "Stylish denim pants for everyday wear.\nSoft and long-lasting fabric.",
      price: "Tk 830",
      image1: "assets/photos/Kids/denim_4_black.jpg",
      image2: "assets/photos/Kids/denim_4_pink.jpg",
      image3: "assets/photos/Kids/denim_4_yellow.jpg",
    ),
    Product(
      id: '90',
      category: "Kids",
      title: "Kids Denim 5",
      description: "Casual denim pants for active children.\nComfortable and durable material.",
      price: "Tk 850",
      image1: "assets/photos/Kids/denim_5_one.jpg",
      image2: "assets/photos/Kids/denim_5_two.jpg",
      image3: "assets/photos/Kids/denim_5_three.jpg",
    ),
  ];
  static List<Product> kidsJackets = [
    Product(
      id: '91',
      category: "Kids",
      title: "Kids Jacket 1",
      description: "Warm jacket suitable for outdoor activities.\nDurable and comfortable.",
      price: "Tk 1200",
      image1: "assets/photos/Kids/jacket_1_1.jpg",
      image2: "assets/photos/Kids/jacket_1_2.jpg",
      image3: "assets/photos/Kids/jacket_1_3.jpg",
    ),
    Product(
      id: '92',
      category: "Kids",
      title: "Kids Jacket 2",
      description: "Comfortable jacket with stylish design.\nIdeal for cold weather outings.",
      price: "Tk 1250",
      image1: "assets/photos/Kids/jacket_2_1.jpg",
      image2: "assets/photos/Kids/jacket_2_2.jpg",
      image3: "assets/photos/Kids/jacket_2_3.jpg",
    ),
    Product(
      id: '93',
      category: "Kids",
      title: "Kids Jacket 3",
      description: "Cozy jacket with soft inner lining.\nPerfect for school and play.",
      price: "Tk 1230",
      image1: "assets/photos/Kids/jacket_3_1.jpg",
      image2: "assets/photos/Kids/jacket_3_2.jpg",
      image3: "assets/photos/Kids/jacket_3_3.jpg",
    ),
    Product(
      id: '94',
      category: "Kids",
      title: "Kids Jacket 4",
      description: "Stylish jacket with durable outer fabric.\nComfortable and easy to wear.",
      price: "Tk 1270",
      image1: "assets/photos/Kids/jacket_4_1.jpg",
      image2: "assets/photos/Kids/jacket_4_2.jpg",
      image3: "assets/photos/Kids/jacket_4_3.jpg",
    ),
    Product(
      id: '95',
      category: "Kids",
      title: "Kids Jacket 5",
      description: "Cozy and warm jacket for outdoor fun.\nSoft lining and durable design.",
      price: "Tk 1290",
      image1: "assets/photos/Kids/jacket_5_1.jpg",
      image2: "assets/photos/Kids/jacket_5_2.jpg",
      image3: "assets/photos/Kids/jacket_5_3.jpg",
    ),
    Product(
      id: '96',
      category: "Kids",
      title: "Kids Jacket 6",
      description: "Durable winter jacket for kids.\nKeeps warm in cold weather.",
      price: "Tk 1300",
      image1: "assets/photos/Kids/jacket_6_1.jpg",
      image2: "assets/photos/Kids/jacket_6_2.jpg",
      image3: "assets/photos/Kids/jacket_6_3.jpg",
    ),
  ];
  static List<Product> kidsCoOrds = [
    Product(
      id: '97',
      category: "Kids",
      title: "Kids Co-ord 1",
      description: "Matching top and bottom set.\nPerfect for casual outings.",
      price: "Tk 1000",
      image1: "assets/photos/Kids/coord_1_pink.jpg",
      image2: "assets/photos/Kids/coord_1_purple.jpg",
      image3: "assets/photos/Kids/coord_1_red.jpg",
    ),
    Product(
      id: '98',
      category: "Kids",
      title: "Kids Co-ord 2",
      description: "Stylish co-ord set for kids.\nSoft and comfortable fabric.",
      price: "Tk 1020",
      image1: "assets/photos/Kids/coord_2_maroon.jpg",
      image2: "assets/photos/Kids/coord_2_pink.jpg",
      image3: "assets/photos/Kids/coord_2_purple.jpg",
    ),
    Product(
      id: '99',
      category: "Kids",
      title: "Kids Co-ord 3",
      description: "Vibrant co-ord set with fun colors.\nDurable and easy to wear.",
      price: "Tk 1030",
      image1: "assets/photos/Kids/coord_3_blue.jpg",
      image2: "assets/photos/Kids/coord_3_brown.jpg",
      image3: "assets/photos/Kids/coord_3_white.jpg",
    ),
    Product(
      id: '100',
      category: "Kids",
      title: "Kids Co-ord 4",
      description: "Comfortable co-ord set for daily wear.\nSoft material for sensitive skin.",
      price: "Tk 1040",
      image1: "assets/photos/Kids/coord_4_black.jpg",
      image2: "assets/photos/Kids/coord_4_blue.jpg",
      image3: "assets/photos/Kids/coord_4_white.jpg",
    ),
    Product(
      id: '101',
      category: "Kids",
      title: "Kids Co-ord 5",
      description: "Stylish top and bottom matching set.\nPerfect for school and casual outings.",
      price: "Tk 1050",
      image1: "assets/photos/Kids/coord_5_blue.jpg",
      image2: "assets/photos/Kids/coord_5_green.jpg",
      image3: "assets/photos/Kids/coord_5_navy.jpg",
    ),
    Product(
      id: '102',
      category: "Kids",
      title: "Kids Co-ord 6",
      description: "Cute co-ord set for kids.\nSoft and breathable material.",
      price: "Tk 1060",
      image1: "assets/photos/Kids/coord_6_pink.jpg",
      image2: "assets/photos/Kids/coord_6_purple.jpg",
      image3: "assets/photos/Kids/coord_6_red.jpg",
    ),
    Product(
      id: '103',
      category: "Kids",
      title: "Kids Co-ord 7",
      description: "Matching top and bottom set.\nComfortable for everyday wear.",
      price: "Tk 1070",
      image1: "assets/photos/Kids/coord_7_black.jpg",
      image2: "assets/photos/Kids/coord_7_blue.jpg",
      image3: "assets/photos/Kids/coord_7_green.jpg",
    ),
  ];
  static List<Product> kids = [
    ...kidsRegular,
    ...kidsNight,
    ...kidsDenims,
    ...kidsJackets,
    ...kidsCoOrds,
  ];

  static List<Product> hats = [
    Product(
      id: '104',
      category: "EcoWear",
      title: "Eco Hat 1",
      description: "Stylish eco-friendly hat made from sustainable materials.\nPerfect for sunny days or casual outings.",
      image1: "assets/photos/Eco/hat_1_1.jpg",
      image2: "assets/photos/Eco/hat_1_2.jpg",
      image3: "assets/photos/Eco/hat_1_3.jpg",
      price: "Tk 890",
    ),
    Product(
      id: '105',
      category: "EcoWear",
      title: "Eco Hat 2",
      description: "Lightweight and breathable, ideal for summer wear.\nCrafted with eco-conscious materials.",
      image1: "assets/photos/Eco/hat_2_1.jpg",
      image2: "assets/photos/Eco/hat_2_2.jpg",
      image3: "assets/photos/Eco/hat_2_3.jpg",
      price: "Tk 920",
    ),
    Product(
      id: '106',
      category: "EcoWear",
      title: "Eco Hat 3",
      description: "Perfect blend of style and sustainability.\nGreat for everyday outdoor use.",
      image1: "assets/photos/Eco/hat_3_1.jpg",
      image2: "assets/photos/Eco/hat_3_2.jpg",
      image3: "assets/photos/Eco/hat_3_3.jpg",
      price: "Tk 950",
    ),
    Product(
      id: '107',
      category: "EcoWear",
      title: "Eco Hat 4",
      description: "Classic design made from recycled fibers.\nAdds eco-chic style to any outfit.",
      image1: "assets/photos/Eco/hat_4_1.jpg",
      image2: "assets/photos/Eco/hat_4_2.jpg",
      image3: "assets/photos/Eco/hat_4_3.jpg",
      price: "Tk 900",
    ),
    Product(
      id: '108',
      category: "EcoWear",
      title: "Eco Hat 5",
      description: "Trendy sustainable hat for all seasons.\nSoft, comfortable, and durable.",
      image1: "assets/photos/Eco/hat_5_1.jpg",
      image2: "assets/photos/Eco/hat_5_2.jpg",
      image3: "assets/photos/Eco/hat_5_3.jpg",
      price: "Tk 940",
    ),
    Product(
      id: '109',
      category: "EcoWear",
      title: "Eco Hat 6",
      description: "Eco-friendly and stylish, perfect for daily wear.\nMade with sustainable materials.",
      image1: "assets/photos/Eco/hat_6_1.jpg",
      image2: "assets/photos/Eco/hat_6_2.jpg",
      image3: "assets/photos/Eco/hat_6_3.jpg",
      price: "Tk 970",
    ),
  ];
  static List<Product> bags = [
    Product(
      id: '110',
      category: "EcoWear",
      title: "Eco Bag 1",
      description: "Compact and durable bag for everyday use.\nMade from environmentally friendly materials.",
      image1: "assets/photos/Eco/bag_1_1.jpg",
      image2: "assets/photos/Eco/bag_1_2.jpg",
      image3: "assets/photos/Eco/bag_1_3.jpg",
      price: "Tk 1250",
    ),
    Product(
      id: '111',
      category: "EcoWear",
      title: "Eco Bag 2",
      description: "Eco-conscious bag with a minimalist design.\nIdeal for shopping or casual outings.",
      image1: "assets/photos/Eco/bag_2_1.jpg",
      image2: "assets/photos/Eco/bag_2_2.jpg",
      image3: "assets/photos/Eco/bag_2_3.jpg",
      price: "Tk 1320",
    ),
    Product(
      id: '112',
      category: "EcoWear",
      title: "Eco Bag 3",
      description: "Stylish sustainable bag for daily essentials.\nMade with durable recycled materials.",
      image1: "assets/photos/Eco/bag_3_1.jpg",
      image2: "assets/photos/Eco/bag_3_2.jpg",
      image3: "assets/photos/Eco/bag_3_3.jpg",
      price: "Tk 1400",
    ),
    Product(
      id: '113',
      category: "EcoWear",
      title: "Eco Bag 4",
      description: "Functional and eco-friendly, fits all your needs.\nPerfect for work or travel.",
      image1: "assets/photos/Eco/bag_4_1.jpg",
      image2: "assets/photos/Eco/bag_4_2.jpg",
      image3: "assets/photos/Eco/bag_4_3.jpg",
      price: "Tk 1380",
    ),
    Product(
      id: '114',
      category: "EcoWear",
      title: "Eco Bag 5",
      description: "Chic and sustainable bag with modern design.\nMade from eco-friendly fabrics.",
      image1: "assets/photos/Eco/bag_5_1.jpg",
      image2: "assets/photos/Eco/bag_5_2.jpg",
      image3: "assets/photos/Eco/bag_5_3.jpg",
      price: "Tk 1450",
    ),
    Product(
      id: '115',
      category: "EcoWear",
      title: "Eco Bag 6",
      description: "Durable and stylish, perfect for daily wear.\nCrafted from sustainable materials.",
      image1: "assets/photos/Eco/bag_6_1.jpg",
      image2: "assets/photos/Eco/bag_6_2.jpg",
      image3: "assets/photos/Eco/bag_6_3.jpg",
      price: "Tk 1500",
    ),
  ];
  static List<Product> footWear = [
    Product(
      id: '116',
      category: "EcoWear",
      title: "Eco Footwear 1",
      description: "Comfortable eco-friendly shoes for everyday use.\nMade from sustainable materials.",
      image1: "assets/photos/Eco/foot_1_1.jpg",
      image2: "assets/photos/Eco/foot_1_2.jpg",
      image3: "assets/photos/Eco/foot_1_3.jpg",
      price: "Tk 1780",
    ),
    Product(
      id: '117',
      category: "EcoWear",
      title: "Eco Footwear 2",
      description: "Stylish and durable, perfect for casual outings.\nCrafted from recycled materials.",
      image1: "assets/photos/Eco/foot_2_1.jpg",
      image2: "assets/photos/Eco/foot_2_2.jpg",
      image3: "assets/photos/Eco/foot_2_3.jpg",
      price: "Tk 1850",
    ),
    Product(
      id: '118',
      category: "EcoWear",
      title: "Eco Footwear 3",
      description: "Modern eco-friendly design with comfort.\nIdeal for walking or daily wear.",
      image1: "assets/photos/Eco/foot_3_1.jpg",
      image2: "assets/photos/Eco/foot_3_2.jpg",
      image3: "assets/photos/Eco/foot_3_3.jpg",
      price: "Tk 1900",
    ),
    Product(
      id: '119',
      category: "EcoWear",
      title: "Eco Footwear 4",
      description: "Sustainable shoes designed for all-day comfort.\nEco-conscious and stylish.",
      image1: "assets/photos/Eco/foot_4_1.jpg",
      image2: "assets/photos/Eco/foot_4_2.jpg",
      image3: "assets/photos/Eco/foot_4_3.jpg",
      price: "Tk 1950",
    ),
    Product(
      id: '120',
      category: "EcoWear",
      title: "Eco Footwear 5",
      description: "Durable and lightweight eco-friendly footwear.\nPerfect for casual or semi-formal wear.",
      image1: "assets/photos/Eco/foot_5_1.jpg",
      image2: "assets/photos/Eco/foot_5_2.jpg",
      image3: "assets/photos/Eco/foot_5_3.jpg",
      price: "Tk 2000",
    ),
    Product(
      id: '121',
      category: "EcoWear",
      title: "Eco Footwear 6",
      description: "Comfortable and sustainable design for daily wear.\nMade from recycled eco materials.",
      image1: "assets/photos/Eco/foot_6_1.jpg",
      image2: "assets/photos/Eco/foot_6_2.jpg",
      image3: "assets/photos/Eco/foot_6_3.jpg",
      price: "Tk 2050",
    ),
  ];
  static List<Product> scarves = [
    Product(
      id: '122',
      category: "EcoWear",
      title: "Eco Scarf 1",
      description: "Soft and eco-friendly scarf, perfect for any outfit.\nMade from sustainable fabrics.",
      image1: "assets/photos/Eco/scarf_1_1.jpg",
      image2: "assets/photos/Eco/scarf_1_2.jpg",
      image3: "assets/photos/Eco/scarf_1_3.jpg",
      price: "Tk 650",
    ),
    Product(
      id: '123',
      category: "EcoWear",
      title: "Eco Scarf 2",
      description: "Lightweight scarf for everyday wear.\nEco-conscious and comfortable.",
      image1: "assets/photos/Eco/scarf_2_1.jpg",
      image2: "assets/photos/Eco/scarf_2_2.jpg",
      image3: "assets/photos/Eco/scarf_2_3.jpg",
      price: "Tk 670",
    ),
    Product(
      id: '124',
      category: "EcoWear",
      title: "Eco Scarf 3",
      description: "Chic sustainable scarf to complement any look.\nSoft, stylish, and eco-friendly.",
      image1: "assets/photos/Eco/scarf_3_1.jpg",
      image2: "assets/photos/Eco/scarf_3_2.jpg",
      image3: "assets/photos/Eco/scarf_3_3.jpg",
      price: "Tk 700",
    ),
    Product(
      id: '125',
      category: "EcoWear",
      title: "Eco Scarf 4",
      description: "Elegant scarf made with recycled materials.\nAdds a sustainable touch to outfits.",
      image1: "assets/photos/Eco/scarf_4_1.jpg",
      image2: "assets/photos/Eco/scarf_4_2.jpg",
      image3: "assets/photos/Eco/scarf_4_3.jpg",
      price: "Tk 720",
    ),
    Product(
      id: '126',
      category: "EcoWear",
      title: "Eco Scarf 5",
      description: "Soft, stylish, and environmentally friendly.\nPerfect for casual and formal wear.",
      image1: "assets/photos/Eco/scarf_5_1.jpg",
      image2: "assets/photos/Eco/scarf_5_2.jpg",
      image3: "assets/photos/Eco/scarf_5_3.jpg",
      price: "Tk 750",
    ),
  ];
  static List<Product> ecoWear = [
    ...hats,
    ...bags,
    ...footWear,
    ...scarves,
  ];

  static List<Product> best=[
    Product(
      id: '88',
      category: "Kids",
      title: "Kids Denim 3",
      description: "Comfortable and durable denim pants.\nEasy to pair with any top.",
      price: "Tk 810",
      image1: "assets/photos/Kids/denim_3_black.jpg",
      image2: "assets/photos/Kids/denim_3_blue.jpg",
      image3: "assets/photos/Kids/denim_3_red.jpg",
    ),
    Product(
      id: '50',
      title:"Soft Neutral Co-Ord",
      category:"Women",
      image1:"assets/photos/Women/coord_4_beige.jpg",
      image2:"assets/photos/Women/coord_4_blue.jpg",
      image3:"assets/photos/Women/coord_4_white.jpg",
      description:"Minimal co-ord outfit with elegant neutral tones.\nComfortable fabric with relaxed fit.",
      price:"Tk 2990",
    ),
    Product(
      id: '34',
      title: "Men's Sweater 1",
      category: "Men",
      image1: "assets/photos/Men/sweater_1_black.jpg",
      image2: "assets/photos/Men/sweater_1_brown.jpg",
      image3: "assets/photos/Men/sweater_1_green.jpg",
      description: "Warm and comfortable sweater.\nPerfect for chilly days and casual outings.",
      price: "Tk 2000",
    ),
    Product(
      id: '99',
      category: "Kids",
      title: "Kids Co-ord 3",
      description: "Vibrant co-ord set with fun colors.\nDurable and easy to wear.",
      price: "Tk 1030",
      image1: "assets/photos/Kids/coord_3_blue.jpg",
      image2: "assets/photos/Kids/coord_3_brown.jpg",
      image3: "assets/photos/Kids/coord_3_white.jpg",
    ),
    Product(
      id: '57',
      title:"Casual Midi Dress",
      category:"Women",
      image1:"assets/photos/Women/dress_3_black.jpg",
      image2:"assets/photos/Women/dress_3_blue.jpg",
      image3:"assets/photos/Women/dress_3_brown.jpg",
      description:"Comfortable midi dress for everyday fashion.\nSoft fabric with relaxed fit.",
      price:"Tk 2450",
    ),
    Product(
      id: '27',
      title: "Men's Pant 1",
      category: "Men",
      image1: "assets/photos/Men/pant_1_black.jpg",
      image2: "assets/photos/Men/pant_1_blue.jpg",
      image3: "assets/photos/Men/pant_1_grey.jpg",
      description: "Comfortable and stylish pants.\nPerfect for casual or office wear.",
      price: "Tk 1500",
    ),
    Product(
      id: '65',
      title:"Minimal Knit Sweater",
      category:"Women",
      image1:"assets/photos/Women/sweater_5_beige.jpg",
      image2:"assets/photos/Women/sweater_5_black.jpg",
      image3:"assets/photos/Women/sweater_5_green.jpg",
      description:"Clean minimalist sweater for modern style.\nWarm and comfortable winter clothing.",
      price:"Tk 2300",
    ),

    Product(
      id: '112',
      category: "EcoWear",
      title: "Eco Bag 3",
      description: "Stylish sustainable bag for daily essentials.\nMade with durable recycled materials.",
      image1: "assets/photos/Eco/bag_3_1.jpg",
      image2: "assets/photos/Eco/bag_3_2.jpg",
      image3: "assets/photos/Eco/bag_3_3.jpg",
      price: "Tk 1400",
    ),
    Product(
      id: '68',
      title:"Casual Cotton Top",
      category:"Women",
      image1:"assets/photos/Women/tops_1_blue.jpg",
      image2:"assets/photos/Women/tops_1_pink.jpg",
      image3:"assets/photos/Women/tops_1_yellow.jpg",
      description:"Soft cotton top perfect for daily outfits.\nComfortable fit with modern design.",
      price:"Tk 1290",
    ),
    Product(
      id: '21',
      title: "Men's Blazer 1",
      category: "Men",
      image1: "assets/photos/Men/blazar_1_blue.jpg",
      image2: "assets/photos/Men/blazar_1_brown.jpg",
      image3: "assets/photos/Men/blazar_1_green.jpg",
      description: "Smart blazer for formal occasions.\nPerfect for office or evening events.",
      price: "Tk 3200",
    ),

    Product(
      id: '118',
      category: "EcoWear",
      title: "Eco Footwear 3",
      description: "Modern eco-friendly design with comfort.\nIdeal for walking or daily wear.",
      image1: "assets/photos/Eco/foot_3_1.jpg",
      image2: "assets/photos/Eco/foot_3_2.jpg",
      image3: "assets/photos/Eco/foot_3_3.jpg",
      price: "Tk 1900",
    ),
    Product(
      id: '15',
      title: "Men's Casual T-Shirt 1",
      category: "Men",
      image1: "assets/photos/Men/tshirt_1_beige.jpg",
      image2: "assets/photos/Men/tshirt_1_blue.jpg",
      image3: "assets/photos/Men/tshirt_1_pink.jpg",
      description: "Soft and breathable cotton t-shirt.\nIdeal for summer and casual outings.",
      price: "Tk 900",
    ),
    Product(
      id: '122',
      category: "EcoWear",
      title: "Eco Scarf 1",
      description: "Soft and eco-friendly scarf, perfect for any outfit.\nMade from sustainable fabrics.",
      image1: "assets/photos/Eco/scarf_1_1.jpg",
      image2: "assets/photos/Eco/scarf_1_2.jpg",
      image3: "assets/photos/Eco/scarf_1_3.jpg",
      price: "Tk 650",
    ),
    Product(
      id: '10',
      title: "Men's Classic Shirt 1",
      category: "Men",
      image1: "assets/photos/Men/shirt_1_black.jpg",
      image2: "assets/photos/Men/shirt_1_blue.jpg",
      image3: "assets/photos/Men/shirt_1_maroon.jpg",
      description: "A comfortable, stylish shirt for daily wear.\nPerfect for casual and semi-formal occasions.",
      price: "Tk 1250",
    ),
    Product(
      id: '1',
      category: "Summer Collection",
      title: "Summer 1",
      description: "Light and breezy summer wear.\nPerfect for hot sunny days.",
      price: "Tk 900",
      image1: "assets/photos/Summer/summer_1_blue_1.jpg",
      image2: "assets/photos/Summer/summer_1_green_1.jpg",
      image3: "assets/photos/Summer/summer_1_pink_1.jpg",
    ),

  ];
  // static List<Product> best=[
  //   Product(
  //     id: '127',
  //     title:"Soft Winter Sweater",
  //     category:"Women",
  //     image1:"assets/photos/Women/sweater_2_beige.jpg",
  //     image2:"assets/photos/Women/sweater_2_black.jpg",
  //     image3:"assets/photos/Women/sweater_2_blue.jpg",
  //     description:"Stylish winter sweater with cozy fabric.\nKeeps you warm while looking elegant.",
  //     price:"Tk 2250",
  //   ),
  //   Product(
  //     id: '128',
  //     category: "Kids",
  //     title: "Kids Co-ord 2",
  //     description: "Stylish co-ord set for kids.\nSoft and comfortable fabric.",
  //     price: "Tk 1020",
  //     image1: "assets/photos/Kids/coord_2_maroon.jpg",
  //     image2: "assets/photos/Kids/coord_2_pink.jpg",
  //     image3: "assets/photos/Kids/coord_2_purple.jpg",
  //   ),
  //   Product(
  //     id: '129',
  //     category: "Summer Collection",
  //     title: "Summer 3",
  //     description: "Soft and airy fabric.\nGreat for casual summer outings.",
  //     price: "Tk 910",
  //     image1: "assets/photos/Summer/summer_3_beige_1.jpg",
  //     image2: "assets/photos/Summer/summer_3_blue_1.jpg",
  //     image3: "assets/photos/Summer/summer_3_green_1.jpg",
  //   ),
  //   Product(
  //     id: '130',
  //     title:"Light Summer Top",
  //     category:"Women",
  //     image1:"assets/photos/Women/tops_5_white_b.jpg",
  //     image2:"assets/photos/Women/tops_5_white_p.jpg",
  //     image3:"assets/photos/Women/tops_5_yellow.jpg",
  //     description:"Light breathable summer top for comfort.\nPerfect for warm weather fashion.",
  //     price:"Tk 1320",
  //   ),
  //   Product(
  //     id: '131',
  //     category: "EcoWear",
  //     title: "Eco Scarf 4",
  //     description: "Elegant scarf made with recycled materials.\nAdds a sustainable touch to outfits.",
  //     image1: "assets/photos/Eco/scarf_4_1.jpg",
  //     image2: "assets/photos/Eco/scarf_4_2.jpg",
  //     image3: "assets/photos/Eco/scarf_4_3.jpg",
  //     price: "Tk 720",
  //   ),
  //   Product(
  //     id: '132',
  //     category: "Kids",
  //     title: "Kids Jacket 1",
  //     description: "Warm jacket suitable for outdoor activities.\nDurable and comfortable.",
  //     price: "Tk 1200",
  //     image1: "assets/photos/Kids/jacket_1_1.jpg",
  //     image2: "assets/photos/Kids/jacket_1_2.jpg",
  //     image3: "assets/photos/Kids/jacket_1_3.jpg",
  //   ),
  //   Product(
  //     id: '133',
  //     title: "Men's Classic Shirt 3",
  //     category: "Men",
  //     image1: "assets/photos/Men/shirt_3_beige.jpg",
  //     image2: "assets/photos/Men/shirt_3_blue.jpg",
  //     image3: "assets/photos/Men/shirt_3_green.jpg",
  //     description: "Elegant shirt with a perfect fit.\nIdeal for work or casual outings.",
  //     price: "Tk 1280",
  //   ),Product(
  //     id: '134',
  //     category: "EcoWear",
  //     title: "Eco Footwear 4",
  //     description: "Sustainable shoes designed for all-day comfort.\nEco-conscious and stylish.",
  //     image1: "assets/photos/Eco/foot_4_1.jpg",
  //     image2: "assets/photos/Eco/foot_4_2.jpg",
  //     image3: "assets/photos/Eco/foot_4_3.jpg",
  //     price: "Tk 1950",
  //   ),
  //   Product(
  //     id: '135',
  //     title: "Men's Casual T-Shirt 4",
  //     category: "Men",
  //     image1: "assets/photos/Men/tshirt_4_blue.jpg",
  //     image2: "assets/photos/Men/tshirt_4_green.jpg",
  //     image3: "assets/photos/Men/tshirt_4_purple.jpg",
  //     description: "Lightweight t-shirt for daily wear.\nKeeps you comfortable in all conditions.",
  //     price: "Tk 940",
  //   ),Product(
  //     id: '136',
  //     title:"Party Style Dress",
  //     category:"Women",
  //     image1:"assets/photos/Women/dress_2_blue.jpg",
  //     image2:"assets/photos/Women/dress_2_maroon.jpg",
  //     image3:"assets/photos/Women/dress_2_violet.jpg",
  //     description:"Stylish party dress with modern silhouette.\nPerfect for celebrations and occasions.",
  //     price:"Tk 2890",
  //   ),Product(
  //     id: '137',
  //     category: "EcoWear",
  //     title: "Eco Bag 4",
  //     description: "Functional and eco-friendly, fits all your needs.\nPerfect for work or travel.",
  //     image1: "assets/photos/Eco/bag_4_1.jpg",
  //     image2: "assets/photos/Eco/bag_4_2.jpg",
  //     image3: "assets/photos/Eco/bag_4_3.jpg",
  //     price: "Tk 1380",
  //   ),
  //   Product(
  //     id: '138',
  //     title: "Men's Blazer 1",
  //     category: "Men",
  //     image1: "assets/photos/Men/blazar_1_blue.jpg",
  //     image2: "assets/photos/Men/blazar_1_brown.jpg",
  //     image3: "assets/photos/Men/blazar_1_green.jpg",
  //     description: "Smart blazer for formal occasions.\nPerfect for office or evening events.",
  //     price: "Tk 3200",
  //   ),Product(
  //     id: '139',
  //     title:"Elegant Two Piece Set",
  //     category:"Women",
  //     image1:"assets/photos/Women/coord_3_blue.jpg",
  //     image2:"assets/photos/Women/coord_3_brown.jpg",
  //     image3:"assets/photos/Women/coord_3_maroon.jpg",
  //     description:"Beautiful coordinated set for a polished style.\nPerfect for outings and casual events.",
  //     price:"Tk 3050",
  //   ),Product(
  //     id: '140',
  //     category: "EcoWear",
  //     title: "Eco Hat 2",
  //     description: "Lightweight and breathable, ideal for summer wear.\nCrafted with eco-conscious materials.",
  //     image1: "assets/photos/Eco/hat_2_1.jpg",
  //     image2: "assets/photos/Eco/hat_2_2.jpg",
  //     image3: "assets/photos/Eco/hat_2_3.jpg",
  //     price: "Tk 920",
  //   ),
  //   Product(
  //     id: '141',
  //     title: "Men's Pant 1",
  //     category: "Men",
  //     image1: "assets/photos/Men/pant_1_black.jpg",
  //     image2: "assets/photos/Men/pant_1_blue.jpg",
  //     image3: "assets/photos/Men/pant_1_grey.jpg",
  //     description: "Comfortable and stylish pants.\nPerfect for casual or office wear.",
  //     price: "Tk 1500",
  //   ),
  //   Product(
  //     id: '142',
  //     title: "Slim Fit Tailored Pants",
  //     category: "Women",
  //     image1: "assets/photos/Women/bottom_3_beige.jpg",
  //     image2: "assets/photos/Women/bottom_3_maroon.jpg",
  //     image3: "assets/photos/Women/bottom_3_white.jpg",
  //     description: "Smart slim-fit pants with a tailored look.\nGreat for professional or smart casual outfits.",
  //     price: "Tk 1990",
  //   ),Product(
  //     id: '143',
  //     title: "Men's Sweater 1",
  //     category: "Men",
  //     image1: "assets/photos/Men/sweater_1_black.jpg",
  //     image2: "assets/photos/Men/sweater_1_brown.jpg",
  //     image3: "assets/photos/Men/sweater_1_green.jpg",
  //     description: "Warm and comfortable sweater.\nPerfect for chilly days and casual outings.",
  //     price: "Tk 2000",
  //   ),
  // ];

}
