import 'package:loop_wear/product.dart';

class MyProducts{
  static List<Product> allProducts=[
    Product(title:"Product name here",
        category:"All Products",
        image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
        price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Product name here",
      category:"All Products",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
  static List<Product> men=[
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Men's Product name",
      category:"Men",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    ];
  static List<Product> women=[
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Women's Product name",
      category:"Women",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
  static List<Product> kids=[
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Kid's Product name",
      category:"Kids",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
  static List<Product> ecoWear=[
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Sustainable Products",
      category:"Ecowear",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
  static List<Product> summer=[
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Summer Products",
      category:"Summer",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
  static List<Product> winter=[
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
    Product(title:"Winter Products",
      category:"Winter",
      image: "https://t4.ftcdn.net/jpg/06/83/67/09/360_F_683670903_y142G40Y2n7Zt22YIyVWUKS2etD8USw9.jpg",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
      price: "Tk 1230",),
  ];
}
